In [2]:
# importing libraries
import numpy as np
import pandas as pd

In [3]:
# reading the data
df = pd.read_csv("hero.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

EDA

In [4]:
df["Actor"]

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [5]:
df["Actor"][3]

'Ranbir Kapoor'

In [6]:
type(df["Actor"])

pandas.core.series.Series

In [ ]:
# only need actor and imdb column
df[["Actor","IMDb"]]

pandas.core.frame.DataFrame

In [15]:
# selecting a row by index
df.loc[0]

# select a row by position whatever the label is
# df.iloc[]

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [ ]:

df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [ ]:
# selecting specific cell using column selection first and row selction second approach
print(df["Actor"][5])

Ayushmann Khurrana

In [ ]:
# selecting specific cell using row selection first and column selection second approach
print(df.loc[5,"Actor"])

Ayushmann Khurrana

In [23]:
# selecting specific cell using iloc
print(df.iloc[5,0])

Ayushmann Khurrana

In [ ]:
# slicing
df.loc[0:2,["Actor","Film","IMDb"]] #includes 0,1,2 . it is inclusive

            Actor             Film  IMDb
0  Shah Rukh Khan          Pathaan   7.2
1     Salman Khan  Tiger Zinda Hai   6.0
2      Aamir Khan           Dangal   8.4

In [29]:
# slicing using iloc
df.iloc[0:2,0:2] #includes 0,1 it is exclusive

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [31]:
# at only accesses one element and it is the fastest
print(df.at[0,"Actor"])
print(df.iat[0,0])

Shah Rukh Khan
Shah Rukh Khan

Filetering using data frame

In [43]:
df[df["IMDb"]>6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [44]:
df[df["IMDb"]>6]["Film"]

0                      Pathaan
2                       Dangal
4                    Padmaavat
5                    Andhadhun
6                        Stree
7                          War
8                   Good Newwz
10       Badrinath Ki Dulhania
11    Uri: The Surgical Strike
Name: Film, dtype: object

In [ ]:
df[(df["IMDb"]>6 ) & (df["Year"]>2018)]

pandas.core.frame.DataFrame

Filtering in data frame using query
1. query always returns a copy of the data frame
2. Column names become variables
3. String values must be in quotes
4. Use backticks for column names with spaces or special characters
5. You can use @ to reference Python variables

In [53]:
df.query("IMDb > 6")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [54]:
df.query("IMDb > 6 and Year==2019")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [60]:
df.query("Actor=='Shah Rukh Khan'")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [70]:
df.query("IMDb>5 and Genre=='Action' | Genre=='Comedy' and Year>2017")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2