In [38]:
# import libraries
import numpy as np
import pandas as pd

In [39]:
# reading dataset
data_url = "https://raw.githubusercontent.com/maruf-git/datasets/refs/heads/main/data_cleaning_sample.csv"
df = pd.read_csv(data_url)
df.head()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019

EDA

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      object
 1   Age        6 non-null      float64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  8 non-null      object
dtypes: float64(1), object(5)
memory usage: 564.0+ bytes

In [41]:
df.columns

Index(['Name', 'Age', 'City', 'Gender', 'Email', 'Join Date'], dtype='object')

In [42]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [43]:
df.describe()
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [44]:
df.shape
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [45]:
df2 = df.fillna(0) # setting 0 to null values

In [46]:
df2.isnull().sum()

Name         0
Age          0
City         0
Gender       0
Email        0
Join Date    0
dtype: int64

In [47]:
mean = df["Age"].mean()
print(mean)

25.833333333333332

In [50]:
# df.fillna({"Age":mean},inplace=True)
df.fillna({"Age":mean})

      Name        Age         City Gender              Email   Join Date
0    Alice  25.000000     New York      F  alice@example.com  01-05-2021
1  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2      Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
4    David  22.000000       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.000000        Delhi      F     eve@domain.com         NaN
6    Alice  25.000000     New York      F  alice@example.com  01-05-2021
7    Alice  25.000000     New York      F  alice@example.com  01-05-2021
8  Charlie  25.833333        Delhi      M    charlie@example  20-07-2021

In [ ]:
# forward fill 
df.fillna(method="ffill") #fills the null cell with the value of forward cell

C:\Users\mun3g\AppData\Local\Temp\ipykernel_12432\2416016099.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [ ]:
# backward fill 
df.fillna(method="bfill") #fills the null cell with the value of backward cell

C:\Users\mun3g\AppData\Local\Temp\ipykernel_12432\2625825578.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill") #fills the null cell with the value of backward cell

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

Remove dupicates

In [54]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [55]:
#remove duplicates
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [56]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [ ]:
df.duplicated(subset=["Name","Age"]) # finds where name and age pair is duplicated

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [ ]:
df.drop_duplicates(subset=["Name","Age"])# removes where name and age pair is duplicated

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

String processing

In [62]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [68]:
# df.query("City=='Delhi'")
df["City"].str.contains("delhi",case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

Applying Functions 
.apply() → Apply any function to rows or columns
.map() → Element-wise mapping for Series
.replace() → Replace specific values

In [70]:
df.dropna(inplace=True)
df

    Name   Age         City Gender              Email   Join Date
0  alice  25.0     New York      F  alice@example.com  01-05-2021
2    bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  david  22.0       Mumbai      M  david@example.com  12-11-2019
6  alice  25.0     New York      F  alice@example.com  01-05-2021
7  alice  25.0     New York      F  alice@example.com  01-05-2021